In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
#define vocab size
voc_size=1000


In [6]:
###One hot encoding
sent=['hai hello, how are you?','Please to see you','Its a beautiful day','Sunset looks good']
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[471, 959, 518, 918, 734],
 [525, 229, 423, 734],
 [520, 444, 768, 618],
 [584, 200, 898]]

In [8]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [9]:
sent_len=8
embedded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_len)
print(embedded_docs)

[[  0   0   0 471 959 518 918 734]
 [  0   0   0   0 525 229 423 734]
 [  0   0   0   0 520 444 768 618]
 [  0   0   0   0   0 584 200 898]]


In [11]:
#featur representation
dim=10
model=Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.compile('adam', 'mse')

e:\Python\Projects\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[ 0.00760077,  0.00943885, -0.04657609, -0.02080914,
          0.01646994,  0.03705574,  0.02403385, -0.03710885,
          0.03151498,  0.04672147],
        [ 0.00760077,  0.00943885, -0.04657609, -0.02080914,
          0.01646994,  0.03705574,  0.02403385, -0.03710885,
          0.03151498,  0.04672147],
        [ 0.00760077,  0.00943885, -0.04657609, -0.02080914,
          0.01646994,  0.03705574,  0.02403385, -0.03710885,
          0.03151498,  0.04672147],
        [-0.04844378, -0.0351102 ,  0.00314592,  0.02525372,
          0.00612545,  0.01114706,  0.01443838,  0.03238578,
          0.01959659,  0.03477776],
        [ 0.04889672, -0.00821805,  0.0457405 ,  0.01909641,
         -0.03929169,  0.00906549, -0.00167489,  0.04974529,
         -0.01379735, -0.03682129],
        [ 0.0399566 , -0.0290141 ,  0.04849337, -0.03175974,
         -0.00245365,  0.01476587, -0.01322649, -0.04107571,
          0.04305545, -0.04496234],
        [-0.00474378,  0.02020801,  0.04886917, -0.0